% EE 122: Cruise Control Example
% 
% The cruise control system of a car is a common feedback system encountered
% in everyday life. The system attempts to maintain a constant velocity in the
% presence of disturbances primarily caused by changes in the slope of a
% road. The controller compensates for these unknowns by measuring the speed
% of the car and adjusting the throttle appropriately.
% 
% This file explores the dynamics and control of the cruise control system,
% following the material presented in Feedback Systems by Astrom and Murray.

clear; clc; close all;

%% Parameters

% Vehicle parameters
m = 1200;                           % mass of vehicle in kg
alpha = [40, 25, 16, 12, 10];       % gear ratios / wheel radius

% PI Controller gains
Kp = 0.5;                           % proportional gain
Ki = 0.1;                           % integral gain

% Simulation parameters
vref = 20;                          % desired velocity (m/s)
gear = 4;                           % use 4th gear
theta = 0;                          % road slope (rad)
T = [0 25];                         % time span

%% Ignore: Find Equilibrium Throttle

% At steady state (v = vref, dv/dt = 0), find throttle needed
equilibrium_fun = @(u) (engine_force(vref, u, gear, alpha) - ...
                        disturbance_force(vref, theta, m)) / m;
u_eq = fzero(equilibrium_fun, 0.5);

%% Simulate Closed-Loop System using ODE45

% State: x = [v; e_integral]
% v = velocity, e_integral = integral of error
x0 = [vref; 0];  % start at reference velocity with zero integral error

% Closed-loop dynamics
cruise_dynamics = @(t, x) cruise_ode(t, x, vref, gear, theta, m, alpha, Kp, Ki);

% Simulate
[t, x] = ode45(cruise_dynamics, T, x0);

% Extract states
v = x(:, 1);           % velocity
e_int = x(:, 2);       % integral of error

% Compute control signal at each time point
u_control = zeros(size(t));
for i = 1:length(t)
    e = vref - v(i);
    u_control(i) = Kp * e + Ki * e_int(i);
end

%% Plot Results

figure;
sgtitle('Response to Change in Road Slope');

% Plot velocity
subplot(2, 1, 1);
plot(t, v, 'LineWidth', 2);
ylabel('Speed [m/s]');
legend(sprintf('m = %d kg', m), 'Location', 'best');
grid on;

% Plot throttle (control input)
subplot(2, 1, 2);
plot(t, u_control, 'LineWidth', 2);
ylabel('Throttle');
xlabel('Time [s]');
grid on;

%% Describe what you simulated and your understanding of the simulations below

% [your text here]

%% ODE Function for Closed-Loop System

function dxdt = cruise_ode(t, x, vref, gear, theta, m, alpha, Kp, Ki)
    % State variables
    v = x(1);           % velocity
    e_int = x(2);       % integral of error
    
    % Error signal
    e = vref - v;
    
    % PI Controller
    u = Kp * e + Ki * e_int;
    
    % Vehicle dynamics
    F = engine_force(v, u, gear, alpha);
    Fd = disturbance_force(v, theta, m);
    dv = (F - Fd) / m;
    
    % Integral error dynamics
    de_int = e;
    
    % State derivatives
    dxdt = [dv; de_int];
end


%% All functions

function torque = motor_torque(omega)
    % MOTOR_TORQUE Engine torque model
    %
    % Parameters:
    %   omega - engine angular speed (rad/s)
    %
    % Returns:
    %   torque - engine torque (N*m)
    
    % Engine parameters
    Tm = 190.0;         % engine torque constant (N*m)
    omega_m = 420.0;    % peak engine angular speed (rad/s)
    beta = 0.4;         % peak engine rolloff
    
    torque = max(0, Tm * (1 - beta * (omega/omega_m - 1)^2));
end

function F = engine_force(v, throttle, gear, alpha)
    % ENGINE_FORCE Force generated by the engine
    %
    % Parameters:
    %   v - vehicle velocity (m/s)
    %   throttle - throttle position [0, 1]
    %   gear - gear number (1-5)
    %   alpha - gear ratios / wheel radius
    %
    % Returns:
    %   F - force (N)
    
    throttle = max(0, min(1, throttle));  % clip to [0, 1]
    omega = alpha(round(gear)) * v;        % engine angular speed
    F = alpha(round(gear)) * motor_torque(omega) * throttle;
end

function Fd = disturbance_force(v, theta, m)
    % DISTURBANCE_FORCE Forces opposing vehicle motion
    %
    % Parameters:
    %   v - vehicle velocity (m/s)
    %   theta - road slope (rad)
    %   m - vehicle mass (kg)
    %
    % Returns:
    %   Fd - total disturbance force (N)
    
    % Vehicle parameters
    g = 9.8;            % gravity (m/s^2)
    Cr = 0.01;          % coefficient of rolling friction
    Cd = 0.32;          % aerodynamic drag coefficient
    rho = 1.3;          % air density (kg/m^3)
    A = 2.4;            % frontal area (m^2)
    
    % Force components
    Fg = m * g * sin(theta);              % gravity
    Fr = m * g * Cr * sign(v);            % rolling friction
    Fa = 0.5 * rho * Cd * A * abs(v) * v; % aerodynamic drag
    
    Fd = Fg + Fr + Fa;
end
