% Basic class for EE 122/ME 141 laboratory reports
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{ee122_labs}[2026/01/05 - v1.0 Standard class for EE 122/ME 141 laboratory reports]
\LoadClass[12pt]{article}
\RequirePackage{ee122_labs}
\typeout{}
\typeout{*** Document Class 'ee122_labs' for EE 122/ME 141 laboratory reports}
\typeout{*** Bugs/comments/suggestions/technicalities via CatCourses.}
\typeout{}
